# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=20, verbose_name='リーグの名前')),
                ('league_date', models.DateField(verbose_name='大会年月日')),
                ('num_of_participant', models.PositiveSmallIntegerField(verbose_name='参加人数')),
                ('whole_winner', models.CharField(blank=True, max_length=20, null=True, verbose_name='大会優勝者')),
            ],
        ),
        migrations.CreateModel(
            name='OneGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_win_set', models.PositiveSmallIntegerField(default=0, verbose_name='A選手獲得セット数')),
                ('B_win_set', models.PositiveSmallIntegerField(default=0, verbose_name='B選手獲得セット数')),
                ('is_A_win', models.NullBooleanField(verbose_name='Aが勝ったか')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.League')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.League')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, verbose_name='参加者名')),
                ('win_num', models.PositiveIntegerField(default=0, verbose_name='勝ち試合数')),
                ('lose_num', models.PositiveIntegerField(default=0, verbose_name='負け試合数')),
                ('total_win_set_num', models.PositiveSmallIntegerField(default=0, verbose_name='勝利セット数')),
                ('total_lose_set_num', models.PositiveSmallIntegerField(default=0, verbose_name='敗北セット数')),
                ('set_rate', models.FloatField(default=0.0, verbose_name='セット率')),
                ('total_win_points', models.PositiveIntegerField(default=0, verbose_name='総獲得得点')),
                ('total_lose_points', models.PositiveIntegerField(default=0, verbose_name='総喪失得点')),
                ('points_rate', models.FloatField(default=0.0, verbose_name='得点率')),
            ],
        ),
        migrations.CreateModel(
            name='SetTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_No', models.PositiveSmallIntegerField(default=0, verbose_name='第nセット')),
                ('A_gain', models.PositiveSmallIntegerField(default=0, verbose_name='A獲得得点')),
                ('B_gain', models.PositiveSmallIntegerField(default=0, verbose_name='B獲得得点')),
                ('game_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.OneGame')),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Player'),
        ),
        migrations.AddField(
            model_name='onegame',
            name='player_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_A', to='fixtures.Player'),
        ),
        migrations.AddField(
            model_name='onegame',
            name='player_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_B', to='fixtures.Player'),
        ),
    ]
